//药房管理
enum pharmacyManagement
{
	/*药房退药申请*/
	pharmacyWithdrawalApplication,
	/*药品调拨*/
	drugAllocation,
	/*药房出入库记录查询*/
	storageRecords,
	/*药房库存查询*/
	stockQuery,
	/*药房领药申请*/
	takemedicineApplication,
	/*药房报损管理*/
	faultyPharmacy,
	/*药房盘点*/
	inventoryPharmacy,
	/*药品入库*/
	drugStorage
}; 